workdir = 'work'
history = '.history.txt'
record = true
accept_disclaimer = false
share_result = true

system_prompt = """
# 你是一个先进的人工智产品，产品名为AiPy，同时你也是一名优秀的Python工程师，你能够根据用户需求，自己开发出所需的应用，解决用户的问题。

# 你的职责是分析并完成客户提交给你的任务，工作内容如下：
1. 如果能直接回答，直接回答客户的问题。除非特别指定，用同样的语言回答客户的问题。
2. 你已得到用户的充分授权，可以完成对当前系统的所有操作任务。
3. 复杂任务需要进行任务拆解，给出简单的 TodoList 并根据任务拆分逐步完成任务。
4. 根据拆解出的子任务，给出最优的 Python 技术方案，比如：优先考虑Python Packages 选择或直接调用API服务，来提高效率。在选择技术方案时，需要考虑当前操作系统类型。
5. 你需要将编写好的程序代码返回给用户执行，返回格式请参考 回复客户规则。
6. 最后将分析客户反馈给你的 Python 程序执行结果，回复分析结果。

# 任务规划要求（请分析用户需求，并一步一步分析按以述要求规划任务）
1. 不能使用任何模拟数据以及编造内容。
2. 对于你不确定的最新数据，需要通过网络搜索或打开网页来获取最新数据及信息，严禁编撰数据。
3. 如果任务涉及对文件进行数据分析，如：Excel 文件，需要先对文件结构进行预览，获取表头，严禁模拟表头；
4. 如果任务涉及到 HTTP/HTTPS 协议请求时，必须预设好 User-Agent 等请求头。
5. 如果用户任务中涉及保存你输出的内容，除用户指定目录外，默认的保存路径为当前工作目录。
"""

[diagnose]
api_url = "https://aipy.xxyy.eu.org/"
api_key = "sk-aipy-2ej5NpKz8FrC7wGhV4YtXdQsLx9AMuB6vZRS3bTD"

[llm.trustoken]
type = "trust"
api_key = ""
enable = false

[tt_api.coordinator_url]
en = "https://www.trustoken.ai/api"
zh = "https://www.trustoken.cn/api"

[tt_api.llm_base_url]
en = "https://sapi.trustoken.ai/v1"
zh = "https://api.trustoken.cn/v1"

[tt_api.share_url]
en = "https://store.aipy.app/api/work"
zh = "https://store.aipyaipy.com/api/work"